//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormgenAssistant.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FormgenAssistant.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://online.adp.com/signin/v1.
        /// </summary>
        internal static string ADP {
            get {
                return ResourceManager.GetString("ADP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://linux.automate.local/cgi-bin/getinfo2.cgi.
        /// </summary>
        internal static string ClientInfoReport {
            get {
                return ResourceManager.GetString("ClientInfoReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to M 0,0 10,16 20,0 10,10 Z.
        /// </summary>
        internal static string DropDownArrowData {
            get {
                return ResourceManager.GetString("DropDownArrowData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://account.activedirectory.windowsazure.com/applications/signin/84239e69-1ea0-48f0-a161-46ae4a2c4f88?tenantId=eb80478c-899d-4783-950d-73b2391d9c7b.
        /// </summary>
        internal static string DSLink {
            get {
                return ResourceManager.GetString("DSLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://solerainc-my.sharepoint.com/:x:/r/personal/felicia_carpenter_solera_com/_layouts/15/doc2.aspx?sourcedoc=%7B11CD9173-C662-4CB0-886A-1D98FB86D55C%7D&amp;file=Forms%20Tracker.xlsx&amp;action=default&amp;mobileredirect=true&amp;DefaultItemOpen=1&amp;cid=b7817432-b777-48c0-ae5d-c94958348e0a.
        /// </summary>
        internal static string FormsTracker {
            get {
                return ResourceManager.GetString("FormsTracker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://dsocket.sharepoint.com/sites/FormsWiki.
        /// </summary>
        internal static string FormsWiki {
            get {
                return ResourceManager.GetString("FormsWiki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/TheHeartOfFire/NewFormgenAssistant.
        /// </summary>
        internal static string GitHub {
            get {
                return ResourceManager.GetString("GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://myapplications.microsoft.com.
        /// </summary>
        internal static string MyApps {
            get {
                return ResourceManager.GetString("MyApps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://account.activedirectory.windowsazure.com/applications/signin/1a282a08-90d5-421b-bac8-3b2c7b9a610e?tenantId=eb80478c-899d-4783-950d-73b2391d9c7b.
        /// </summary>
        internal static string Outlook {
            get {
                return ResourceManager.GetString("Outlook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://account.activedirectory.windowsazure.com/applications/signin/16d2b7b8-7000-4c9c-8476-212e03ddea4c?tenantId=c45b48f3-13bb-448b-9356-ba7b863c2189.
        /// </summary>
        internal static string SalesForce {
            get {
                return ResourceManager.GetString("SalesForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://wd5.myworkday.com/solera/d/home.htmld.
        /// </summary>
        internal static string Workday {
            get {
                return ResourceManager.GetString("Workday", resourceCulture);
            }
        }
    }
}
